-- Amani Tech — seed data (illustrative content for development/review; replace before launch)

-- ---------- Categories ----------
insert into categories (name, slug, sort_order) values
 ('IT & Software','it',1), ('Finance & Accounting','finance',2), ('Engineering','engineering',3),
 ('Operations & Supply Chain','operations',4), ('Sales & Marketing','sales',5), ('HR & Administration','hr',6);

insert into subcategories (category_id, name, slug, sort_order)
select c.id, s.name, s.slug, s.ord from categories c join (values
 ('it','Software Development','software-development',1),('it','Cloud & DevOps','cloud-devops',2),('it','Data Engineering','data-engineering',3),
 ('it','Data Science','data-science',4),('it','AI / ML','ai-ml',5),('it','Cybersecurity','cybersecurity',6),('it','QA / Automation','qa-automation',7),
 ('it','ERP','erp',8),('it','IT Project Management','it-project-management',9),
 ('finance','Accounting','accounting',1),('finance','Banking','banking',2),('finance','Financial Analysis','financial-analysis',3),('finance','Audit','audit',4),
 ('engineering','Mechanical','mechanical',1),('engineering','Civil','civil',2),('engineering','Electrical','electrical',3),('engineering','Electronics','electronics',4),
 ('operations','Logistics','logistics',1),('operations','Procurement','procurement',2),('operations','Plant Operations','plant-operations',3),
 ('sales','Inside Sales','inside-sales',1),('sales','Field Sales','field-sales',2),('sales','Digital Marketing','digital-marketing',3),
 ('hr','Recruitment','recruitment',1),('hr','HR Operations','hr-operations',2),('hr','Administration','administration',3)
) as s(cat, name, slug, ord) on s.cat = c.slug;

-- ---------- Services ----------
insert into services (slug, title, short_description, long_description, icon, image, roles, sort_order) values
 ('it-staffing','IT Staffing','Developers, cloud and DevOps engineers, data and AI specialists, QA, ERP and IT project managers — on contract or permanent terms.','Software, cloud, data, security and QA professionals — screened for real skills, not just keywords.','code','https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1200&q=80', array['Software Development','Cloud & DevOps','Data Engineering','Data Science','AI / ML','Cybersecurity','QA / Automation','ERP','IT Project Management'],1),
 ('non-it-staffing','Non-IT Staffing','Finance, accounting, engineering, operations, sales and support roles across industries.','Finance, engineering, operations, sales and support hiring with the same rigour we apply to technology roles.','briefcase','https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1200&q=80', array['Accounting','Financial Analysis','Mechanical','Electrical','Procurement','Logistics','Inside Sales','HR Operations'],2),
 ('contract-staffing','Contract Staffing','Flexible, compliant workforce for project peaks, backfills and fixed-term needs.','Compliant contract workforce for peaks, backfills and fixed-term projects — on our payroll, deployed to you.','clock','https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80', array['Developers','QA','Site engineers','Support staff','Analysts'],3),
 ('permanent-recruitment','Permanent Recruitment','End-to-end hiring for full-time positions, from brief to offer acceptance.','Full-cycle recruitment for roles you need to get right the first time.','usercheck','https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80', array['Leadership','Specialists','Managers','Individual contributors'],4),
 ('bulk-project-hiring','Bulk & Project Hiring','Volume hiring for new sites, expansions and time-bound programmes.','Volume hiring for new facilities, expansions and time-bound programmes, with structured screening at scale.','users','https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80', array['Sales teams','Plant staff','Support centres','Field engineers'],5),
 ('fresher-hiring','Fresher & Entry-Level Hiring','Screened graduates and early-career talent ready to start.','Screened graduates and early-career candidates, assessed for aptitude and attitude.','graduation','https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1200&q=80', array['Graduate engineers','Trainee analysts','Associate recruiters','Sales trainees'],6),
 ('training-upskilling','Training & Upskilling','Role-ready training for graduates and working professionals, aligned to what employers are hiring for now.','Short, practical programmes that close the gap between a candidate and a role — technical foundations, tools, communication and interview readiness — delivered before placement or as part of a hiring drive.','trend','https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80', array['Pre-placement bootcamps','Employer-specific onboarding','Software & cloud foundations','Communication & interview skills'],7);

-- ---------- FAQs ----------
insert into faqs ("group", question, answer, sort_order) values
 ('Job seekers','Do job seekers pay anything to apply?','No. Amani Tech never charges candidates for registration, applications or placements.',1),
 ('Job seekers','How do I know a job is genuine?','Every job on this site is posted by Amani Tech’s recruitment team after confirming the requirement with the employer.',2),
 ('Job seekers','What happens after I apply?','You receive a confirmation email. A recruiter reviews your application and contacts you if the role is a fit. You can check your status in your dashboard.',3),
 ('Job seekers','Which resume formats do you accept?','PDF, DOC and DOCX up to 5 MB.',4),
 ('Job seekers','Can I apply to more than one job?','Yes. Register once and apply to as many relevant roles as you like.',5),
 ('Employers','How quickly can employers expect a shortlist?','For most roles, profiles are shared within a few working days of the requirement being confirmed.',6),
 ('Employers','Do you offer contract staffing?','Yes. We provide contract, permanent and project-based staffing.',7),
 ('Employers','Do you place non-IT candidates?','Yes — finance, engineering, operations, sales, support and more.',8),
 ('Employers','Which locations do you cover?','We place candidates across major Indian cities and remote roles. Tell us the location in your requirement and we will confirm coverage.',9),
 ('Partners','Who can become a staffing partner?','Specialist staffing firms, regional agencies, campus partners and independent recruiters with a strong candidate network.',10),
 ('General','How is my data used?','Your resume is only shared with employers for roles you apply to. See our Privacy Policy for details.',11),
 ('General','How do I contact Amani Tech?','Use the contact page, email hello@amanitech.in or call +91 40 0000 0000 during office hours.',12);

-- ---------- Site content ----------
insert into site_content (key, payload, is_visible) values
 ('hero', '{"eyebrow":"Staffing & Recruitment · IT and Non-IT","heading":"Find work that moves your career forward.","accent":"career forward.","subheading":"Amani Tech connects skilled professionals with verified employers across IT and non-IT roles. Search open positions, apply in minutes, and let our recruitment team support you through every step.","primary_cta":"Search Jobs","secondary_cta":"Hiring? Request talent","secondary_url":"/employers","popular":["Java Developer","Data Engineer","Accountant","DevOps","Mechanical Engineer"],"image":"https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80"}', true),
 ('trust_band', '{"heading":"Trusted by employers across industries","industries":["IT Services","Banking & Finance","Manufacturing","Healthcare","Retail & E-commerce","Education","Logistics","Telecom"],"logos":[]}', true),
 ('statistics', '{"items":[{"number":1200,"suffix":"+","label":"Candidates placed"},{"number":180,"suffix":"+","label":"Client companies"},{"number":25,"suffix":"+","label":"Job categories"},{"number":9,"suffix":"","label":"Years in staffing"}]}', true),
 ('employer_cta', '{"heading":"Looking for the right talent?","text":"Tell us about the role. Our recruiters will source, screen and shortlist candidates for you.","primary_cta":"Request Talent","secondary_cta":"Become a staffing partner"}', true),
 ('footer', '{"description":"Amani Tech helps job seekers find genuine opportunities and helps employers hire the right people — across IT and non-IT roles.","address":"4th Floor, Tech Park Tower, HITEC City, Hyderabad 500081, India","phone":"+91 40 0000 0000","email":"hello@amanitech.in","hours":"Mon–Sat, 9:30 AM – 6:30 PM IST","social":{"linkedin":"","instagram":"","x":"","youtube":""}}', true),
 ('settings', '{"site_name":"Amani Tech","seo_suffix":"| Amani Tech","seo_description":"Find genuine job opportunities or hire screened talent. Amani Tech connects candidates and employers across IT and non-IT roles in India.","employer_sla":"within one business day","notify_emails":"recruitment@amanitech.in, employers@amanitech.in"}', true);

-- ---------- Jobs ----------
insert into jobs (slug, title, company_name, location, work_mode, employment_type, exp_min, exp_max, salary_min, salary_max, category_id, subcategory_id, skills, published_at, application_deadline, is_featured, status, job_source, qualification, description, responsibilities, requirements, benefits)
select j.slug, j.title, j.company, j.location, j.mode, j.etype, j.emin, j.emax, j.smin, j.smax,
       (select id from categories where slug = j.cat), (select s.id from subcategories s join categories c on c.id = s.category_id where c.slug = j.cat and s.slug = j.sub),
       j.skills, j.posted::timestamptz, j.deadline::date, j.featured, 'PUBLISHED', j.source, j.qual, j.descr, j.resp, j.reqs, j.bens
from (values
 ('senior-java-developer-hyderabad','Senior Java Developer','Finserv Product Company','Hyderabad','Hybrid','Full-time',5,8,18,26,'it','software-development',array['Java','Spring Boot','Microservices','AWS','Kafka'],'2026-09-14','2026-10-10',true,'Direct client','B.E. / B.Tech / MCA in Computer Science or related field','A financial services product company is expanding its core payments platform team. You will design and build high-throughput backend services in Java and Spring Boot, working closely with architects and product owners on features that handle millions of transactions daily.',array['Design, develop and maintain microservices using Java 17 and Spring Boot','Own features end to end — from technical design through deployment and monitoring','Review code and mentor two to three mid-level engineers','Collaborate with QA and DevOps on CI/CD and release quality','Participate in on-call rotation for production support'],array['5–8 years of hands-on Java development','Strong experience with Spring Boot, REST APIs and relational databases','Working knowledge of Kafka or similar messaging systems','Experience deploying to AWS (ECS, RDS, S3)','Clear written and verbal communication'],array['Health insurance for family','Hybrid working (3 days in office)','Annual performance bonus','Learning and certification budget']),
 ('devops-engineer-bengaluru','DevOps Engineer','SaaS Scale-up','Bengaluru','On-site','Full-time',3,6,14,22,'it','cloud-devops',array['Kubernetes','Terraform','AWS','GitHub Actions','Prometheus'],'2026-09-13','2026-10-05',true,'Direct client','B.E. / B.Tech or equivalent experience','Join a fast-growing SaaS company to own infrastructure and delivery pipelines across multiple environments. You will automate everything that can be automated and make deployments boring.',array['Manage Kubernetes clusters on AWS EKS','Write and maintain Terraform modules for all infrastructure','Build and optimise CI/CD pipelines in GitHub Actions','Set up observability with Prometheus, Grafana and alerting','Drive cost optimisation and security hardening'],array['3–6 years in DevOps or SRE roles','Production experience with Kubernetes and Terraform','Solid Linux and networking fundamentals','Scripting in Bash or Python','AWS certification is a plus'],array['ESOPs','Health insurance','Free meals','Relocation assistance']),
 ('data-engineer-pune','Data Engineer','Global Analytics Firm','Pune','Hybrid','Full-time',3,7,15,24,'it','data-engineering',array['Python','Spark','Airflow','Snowflake','SQL'],'2026-09-12','2026-10-12',true,'Direct client','Bachelor’s degree in Engineering, Statistics or related field','Build and operate data pipelines that feed analytics for retail and consumer clients. You will work with Spark, Airflow and Snowflake and own data quality for your domain.',array['Design and build batch and streaming pipelines','Model data in Snowflake for analytics consumption','Implement data quality checks and monitoring','Partner with analysts and data scientists on requirements'],array['3+ years building data pipelines in production','Strong SQL and Python','Hands-on with Spark and an orchestration tool (Airflow preferred)','Experience with a cloud data warehouse'],array['Hybrid working','Health and accident insurance','Certification reimbursement']),
 ('accountant-mumbai','Accountant','Manufacturing Group','Mumbai','On-site','Full-time',2,5,4.5,7,'finance','accounting',array['Tally','GST','TDS','MS Excel','Bank reconciliation'],'2026-09-11','2026-10-01',false,'Direct client','B.Com / M.Com; CA Inter preferred','Handle day-to-day accounting for a manufacturing group with three plants. Accurate books, timely compliance and clean month-end closes are the core of this role.',array['Post journal entries and maintain ledgers in Tally','Prepare GST and TDS returns','Reconcile bank and vendor accounts monthly','Support statutory audits with schedules and documentation'],array['2–5 years of accounting experience','Working knowledge of GST and TDS','Comfort with Tally and Excel','Attention to detail'],array['Provident fund','Health insurance','Annual bonus']),
 ('mechanical-design-engineer-chennai','Mechanical Design Engineer','Automotive Components Manufacturer','Chennai','On-site','Full-time',3,6,6,10,'engineering','mechanical',array['SolidWorks','CATIA','GD&T','DFMEA','Sheet metal'],'2026-09-10','2026-10-08',true,'Direct client','B.E. / B.Tech in Mechanical Engineering','Design sheet-metal and plastic components for two-wheeler platforms. You will take parts from concept to production release, working with tooling and quality teams.',array['Create 3D models and 2D drawings in SolidWorks / CATIA','Apply GD&T and tolerance stack-up analysis','Run DFMEA and support validation testing','Coordinate with suppliers on tooling feasibility'],array['3–6 years in automotive component design','Proficiency in SolidWorks or CATIA','Understanding of manufacturing processes for sheet metal and plastics'],array['Transport facility','Subsidised canteen','Health insurance']),
 ('qa-automation-engineer-remote','QA Automation Engineer','HealthTech Platform','Remote','Remote','Contract',2,5,9,15,'it','qa-automation',array['Selenium','Playwright','Java','REST Assured','CI/CD'],'2026-09-15','2026-09-30',false,'Staffing partner','Any graduate with relevant experience','Twelve-month contract (extendable) with a healthcare technology company. Build and maintain automated test suites for web and API layers.',array['Write and maintain UI automation in Playwright or Selenium','Automate API tests with REST Assured','Integrate suites into CI pipelines','Report defects with clear reproduction steps'],array['2–5 years in test automation','Strong Java or TypeScript','Experience testing REST APIs','Comfortable working in a fully remote team'],array['Fully remote','Contract on Amani Tech payroll with benefits','Extension based on performance']),
 ('financial-analyst-gurugram','Financial Analyst','NBFC','Gurugram','Hybrid','Full-time',2,4,8,12,'finance','financial-analysis',array['Financial modelling','Excel','Power BI','Budgeting','Variance analysis'],'2026-09-09','2026-10-09',false,'Direct client','MBA (Finance) / CA / CFA Level 1+','Support the FP&A team of a growing NBFC with budgeting, forecasting and management reporting.',array['Build and maintain financial models','Prepare monthly MIS and variance analysis','Support annual budgeting and quarterly forecasts','Automate reports in Power BI'],array['2–4 years in FP&A or financial analysis','Advanced Excel; Power BI a plus','Strong analytical and presentation skills'],array['Hybrid working','Health insurance','Performance bonus']),
 ('cybersecurity-analyst-hyderabad','Cybersecurity Analyst (SOC L2)','IT Services Company','Hyderabad','On-site','Full-time',3,6,10,16,'it','cybersecurity',array['SIEM','Splunk','Incident response','Threat hunting','CEH'],'2026-09-08','2026-10-15',false,'Direct client','B.E. / B.Tech; CEH or equivalent certification preferred','Work in a 24×7 security operations centre handling escalated alerts, investigations and incident response for enterprise clients.',array['Triage and investigate escalated SIEM alerts','Lead incident response and document findings','Tune detection rules and reduce false positives','Mentor L1 analysts'],array['3–6 years in SOC or security operations','Hands-on with Splunk or a comparable SIEM','Understanding of MITRE ATT&CK','Willing to work in rotational shifts'],array['Shift allowance','Health insurance','Certification sponsorship']),
 ('sap-fico-consultant-bengaluru','SAP FICO Consultant','Global Consulting Firm','Bengaluru','Hybrid','Full-time',6,10,22,32,'it','erp',array['SAP FICO','S/4HANA','GL','AP/AR','Asset accounting'],'2026-09-07','2026-10-20',true,'Direct client','CA / MBA (Finance) / B.Com with SAP certification','Lead FICO workstreams on S/4HANA implementation and rollout projects for manufacturing and pharma clients.',array['Gather requirements and design FICO solutions','Configure GL, AP, AR, Asset Accounting and Controlling','Lead testing cycles and cutover activities','Support post-go-live stabilisation'],array['6–10 years of SAP FICO experience with at least two end-to-end implementations','S/4HANA project experience','Strong understanding of finance processes'],array['Hybrid working','Health insurance','International project opportunities']),
 ('inside-sales-executive-pune','Inside Sales Executive','EdTech Company','Pune','On-site','Full-time',1,3,3.5,6,'sales','inside-sales',array['Lead qualification','CRM','Cold calling','Negotiation'],'2026-09-15','2026-10-02',false,'Direct client','Any graduate','Convert inbound leads into enrolments for professional upskilling programmes. Target-driven role with uncapped incentives.',array['Call and qualify inbound leads','Run product demos and follow-ups','Maintain pipeline in CRM','Meet monthly enrolment targets'],array['1–3 years in inside sales or telesales','Fluent English and Hindi','Comfortable with targets'],array['Uncapped incentives','Health insurance','Fast-track promotion path']),
 ('electrical-engineer-hyderabad','Electrical Engineer — Projects','EPC Contractor','Hyderabad','On-site','Contract',4,8,7,11,'engineering','electrical',array['HT/LT systems','AutoCAD Electrical','Substation','Site execution'],'2026-09-06','2026-09-28',false,'Direct client','B.E. / B.Tech in Electrical Engineering','Eighteen-month project contract on an industrial park electrification project. Site-based role with execution ownership.',array['Review electrical drawings and BOQs','Supervise HT/LT installation and testing','Coordinate with vendors and client engineers','Ensure safety compliance on site'],array['4–8 years in electrical project execution','Substation and HT/LT experience','Willing to be site-based'],array['Site allowance','Accommodation','Health insurance']),
 ('machine-learning-engineer-remote','Machine Learning Engineer','AI Product Start-up','Remote','Remote','Full-time',3,6,20,30,'it','ai-ml',array['Python','PyTorch','MLOps','LLMs','AWS SageMaker'],'2026-09-14','2026-10-14',true,'Direct client','B.Tech / M.Tech in CS, Statistics or related','Take models from notebook to production. You will own training pipelines, evaluation and serving for a document-intelligence product.',array['Build and maintain training and inference pipelines','Fine-tune and evaluate LLM-based components','Implement monitoring for model drift','Collaborate with backend engineers on serving APIs'],array['3–6 years in ML engineering','Strong Python and PyTorch','Production MLOps experience','Familiarity with LLM fine-tuning and evaluation'],array['Fully remote','ESOPs','Health insurance','Home office budget']),
 ('hr-recruiter-hyderabad','HR Recruiter (Non-IT)','Retail Chain','Hyderabad','On-site','Full-time',1,4,3,5,'hr','recruitment',array['Sourcing','Screening','Bulk hiring','Job portals','Onboarding'],'2026-09-05','2026-09-30',false,'Direct client','Any graduate; MBA (HR) preferred','Handle bulk hiring for store and warehouse roles across Telangana and Andhra Pradesh.',array['Source candidates via portals, references and drives','Screen and schedule interviews','Coordinate offers and onboarding','Maintain hiring trackers'],array['1–4 years in recruitment, preferably volume hiring','Telugu and English fluency','Organised and target-oriented'],array['Provident fund','Health insurance','Incentives on closures']),
 ('procurement-executive-chennai','Procurement Executive','Pharma Manufacturer','Chennai','On-site','Full-time',2,5,4,6.5,'operations','procurement',array['Vendor management','SAP MM','Negotiation','Purchase orders'],'2026-09-04','2026-10-04',false,'Direct client','B.Pharm / B.Sc / B.E. with supply chain exposure','Manage raw material and packaging procurement for a pharma formulation plant.',array['Raise and track purchase orders in SAP MM','Negotiate with approved vendors','Monitor deliveries and resolve discrepancies','Maintain vendor performance records'],array['2–5 years in procurement, pharma preferred','SAP MM experience','Good negotiation skills'],array['Transport','Canteen','Health insurance']),
 ('frontend-developer-react-hyderabad','Frontend Developer (React)','Digital Agency','Hyderabad','Hybrid','Full-time',2,4,8,13,'it','software-development',array['React','TypeScript','Next.js','CSS','REST'],'2026-09-16','2026-10-16',false,'Direct client','Any graduate with relevant portfolio','Build responsive, accessible web interfaces for clients in retail and hospitality. You will work directly with designers and backend engineers.',array['Implement UI from Figma designs in React and TypeScript','Optimise performance and accessibility','Write unit tests and participate in code reviews'],array['2–4 years with React','Solid TypeScript and modern CSS','Experience with Next.js is a plus'],array['Hybrid working','Health insurance','Learning budget']),
 ('graduate-trainee-engineer-pune','Graduate Trainee Engineer','Industrial Automation Company','Pune','On-site','Full-time',0,1,3.5,4.5,'engineering','electronics',array['PLC basics','Electronics','Problem solving'],'2026-09-13','2026-10-13',false,'Campus partner','B.E. / B.Tech (2025 or 2026 batch) in Electronics, Instrumentation or Electrical','A one-year structured trainee programme with rotations across design, testing and field service, leading to a permanent engineer role.',array['Learn and support PLC panel design and testing','Assist senior engineers on customer sites','Document test results and procedures'],array['Fresh graduate or up to 1 year of experience','Strong fundamentals in electronics','Willingness to travel'],array['Structured training','Health insurance','Confirmation after 12 months']),
 ('it-project-manager-mumbai','IT Project Manager','Banking Technology Provider','Mumbai','Hybrid','Full-time',8,12,25,35,'it','it-project-management',array['PMP','Agile','Stakeholder management','Banking domain','JIRA'],'2026-09-02','2026-10-02',false,'Direct client','B.E. / MBA; PMP or PRINCE2 preferred','Deliver core banking implementation projects for private-sector banks. Manage scope, schedule, budget and a cross-functional team of 20+.',array['Plan and track delivery across multiple workstreams','Manage client stakeholders and steering committees','Own risk, issue and change management','Report status to leadership'],array['8–12 years in IT delivery with 4+ as project manager','Banking or financial services domain experience','PMP or equivalent certification'],array['Hybrid working','Health insurance','Performance bonus'])
) as j(slug, title, company, location, mode, etype, emin, emax, smin, smax, cat, sub, skills, posted, deadline, featured, source, qual, descr, resp, reqs, bens);

-- ---------- Blog ----------
insert into blog_posts (slug, title, category, excerpt, tags, read_minutes, is_featured, status, published_at, cover_image, content) values
 ('resume-a-recruiter-will-read','How to write a resume that a recruiter will actually read','Career Advice','Recruiters spend under a minute on a first pass. Here is how to make that minute count — structure, keywords, and the mistakes that get resumes skipped.',array['Resume','Job search'],6,true,'PUBLISHED','2026-09-10','https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=1600&q=80',
  E'## Start with the reader, not with yourself\n\nMost resumes are written for the person writing them. The recruiter reading it is looking for a fast answer to three questions: does this person do the kind of work the role needs, at the level the role needs, in a way that suggests they will succeed here? Everything on the page should serve one of those questions.\n\n## Lead with the evidence\n\nPut your most relevant experience in the first third of the page. Use the language of the job description where it is honest to do so — a recruiter scanning for "Kafka" or "GST filing" should find it without hunting. Numbers help: team size, systems handled, budgets, volumes.\n\n## Cut what does not help\n\nObjectives, declarations, hobbies and long lists of every tool you have ever touched rarely move a decision. If a line would not change a recruiter\'s mind, remove it. Two focused pages beat four unfocused ones.\n\n## Make it easy to contact you\n\nPhone, email and city at the top. A working LinkedIn URL if you have one. Recruiters will call — make sure they can.'),
 ('contract-vs-permanent-hiring','Contract vs permanent hiring: which is right for your team?','Insights','Both models work — for different situations. A practical framework for choosing, with the cost and speed trade-offs employers usually miss.',array['Hiring','Contract staffing'],5,false,'PUBLISHED','2026-09-03','https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1600&q=80',
  E'## Start with the shape of the work\n\nIf the work has a clear end date, a variable volume, or needs a skill you will not need again for a while, contract staffing usually wins. If the work is core, ongoing and benefits from institutional memory, hire permanently.\n\n## Count the real cost\n\nContract rates look higher per month but include payroll, compliance and replacement risk. Permanent hires cost less per month but carry recruitment time, notice periods and the cost of a wrong hire.\n\n## Speed matters more than people admit\n\nA contract engineer can start in days. A permanent senior hire takes 60–90 days including notice. If a project is waiting, that gap is the most expensive line on the sheet.'),
 ('questions-before-accepting-an-offer','The 5 questions to ask before accepting a job offer','Career Advice','Salary is only one line. Ask these five questions and you will avoid the most common regrets we hear from candidates.',array['Offers','Career growth'],4,false,'PUBLISHED','2026-08-27','https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1600&q=80',
  E'## 1. What does success look like in six months?\n\nIf the manager cannot answer, the role is not defined yet.\n\n## 2. Who will I learn from?\n\nGrowth comes from people, not job titles.\n\n## 3. What happened to the last person in this role?\n\nPromoted, moved, or left — each tells you something.\n\n## 4. How are decisions made here?\n\nAsk for a recent example.\n\n## 5. What is not in the offer letter?\n\nHybrid days, review cycles, notice periods, bonus conditions. Get them in writing.'),
 ('hiring-cloud-devops-2026','Hiring for cloud and DevOps in 2026: what employers are looking for','Insights','Platform engineering, cost ownership and security-by-default have moved from nice-to-have to baseline. What that means for job descriptions and screening.',array['DevOps','Hiring trends'],7,false,'PUBLISHED','2026-08-20','https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80',
  E'## Platform, not just pipelines\n\nEmployers now expect DevOps engineers to build internal platforms that developers self-serve from, not just maintain CI.\n\n## Cost is a skill\n\nCandidates who can read a cloud bill and act on it are scarce and valued.\n\n## Security by default\n\nIAM hygiene, secrets management and supply-chain scanning are screening questions now, not bonuses.'),
 ('technical-interview-domain-switch','Preparing for a technical interview when you are switching domains','Career Advice','Moving from services to product, or from one industry to another? How to frame your experience so interviewers see transferable depth, not gaps.',array['Interviews'],5,false,'PUBLISHED','2026-08-13','https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1600&q=80',
  E'## Translate, do not apologise\n\nMap your past work to the new domain\'s vocabulary before the interview. Every industry has its own words for "throughput", "compliance" and "customer".\n\n## Bring one deep story\n\nOne problem you solved end to end beats ten bullet points.\n\n## Ask domain questions back\n\nCuriosity about the new domain is the strongest signal you will ramp fast.'),
 ('non-it-hiring-deserves-rigour','Why non-IT hiring deserves the same rigour as tech hiring','Insights','Plant engineers, accountants and sales teams carry as much business risk as developers. A case for structured screening beyond IT.',array['Non-IT','Screening'],4,false,'PUBLISHED','2026-08-06','https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1600&q=80',
  E'## The cost of a wrong hire is not smaller\n\nA plant engineer who misses a tolerance or an accountant who misfiles GST creates real losses.\n\n## Structured screening works everywhere\n\nWork-sample questions, reference checks and clear scorecards apply to any role.\n\n## What we do differently\n\nWe screen non-IT candidates on the actual tasks of the job, not just tenure.');

-- ---------- Career openings ----------
insert into career_openings (slug, position, department, location, work_mode, experience, status, published_at, description, responsibilities, requirements, benefits, application_instructions) values
 ('senior-it-recruiter','Senior IT Recruiter','Recruitment','Hyderabad','Hybrid','4–7 years','PUBLISHED','2026-09-08','Own end-to-end recruitment for IT mandates — from understanding the requirement with the client to offer negotiation and joining.',array['Understand client requirements and build search strategies','Source, screen and present candidates with recruiter notes','Manage the candidate experience through interviews and offers','Mentor associate recruiters'],array['4–7 years in IT recruitment, agency experience preferred','Strong sourcing skills across portals, LinkedIn and referrals','Excellent communication and follow-through'],array['Health insurance','Performance incentives','Hybrid working','Learning budget'],'Email your resume to careers@amanitech.in with the subject line “Senior IT Recruiter”. Include a short note on the toughest role you have closed.'),
 ('account-manager-staffing','Account Manager — Staffing','Client Services','Bengaluru','Hybrid','5–9 years','PUBLISHED','2026-09-01','Grow and manage relationships with employer clients, ensuring requirements are understood, staffed on time and renewed.',array['Manage a portfolio of employer accounts','Translate requirements into clear briefs for the recruitment team','Track delivery, escalate risks and drive renewals','Identify expansion opportunities'],array['5–9 years in staffing account management or B2B client services','Understanding of contract and permanent staffing models','Commercial acumen'],array['Health insurance','Quarterly incentives','Hybrid working'],'Email your resume to careers@amanitech.in with the subject line “Account Manager — Staffing”.'),
 ('associate-recruiter-non-it','Associate Recruiter (Non-IT)','Recruitment','Hyderabad','On-site','0–2 years','PUBLISHED','2026-09-12','Start your recruitment career with structured training. You will support senior recruiters on finance, engineering and operations mandates.',array['Source candidates from portals and databases','Conduct first-level screening calls','Maintain trackers and schedule interviews'],array['0–2 years of experience; graduates welcome','Clear spoken and written English; Telugu or Hindi a plus','Curiosity about people and industries'],array['Structured onboarding','Health insurance','Clear promotion path'],'Email your resume to careers@amanitech.in with the subject line “Associate Recruiter”.'),
 ('full-stack-developer-internal','Full-Stack Developer (Internal Platform)','Technology','Remote','Remote','3–5 years','PUBLISHED','2026-08-25','Build and maintain the Amani Tech job platform and admin tools used by our recruiters every day.',array['Ship features across the Next.js frontend and Supabase backend','Maintain the PostgreSQL schema and API','Improve performance, accessibility and security'],array['3–5 years with TypeScript, React and Node','Experience with PostgreSQL and file storage','Product mindset'],array['Fully remote','Health insurance','Learning budget'],'Email your resume and a link to something you have built to careers@amanitech.in with the subject line “Full-Stack Developer”.');

-- ---------- Testimonials (illustrative — replace with real, approved reviews) ----------
insert into testimonials (name, designation, company, rating, review, status, is_featured, approved_at) values
 ('Priya Raman','Data Engineer','Placed via Amani Tech',5,'I had applied to dozens of portals with no response. Within a week of applying here, a recruiter called me, explained the role honestly, and prepared me for the interview. I joined in three weeks.','APPROVED',true,now()),
 ('Suresh Menon','Head of Engineering','SaaS Scale-up',5,'We needed two DevOps engineers before a product launch. Amani Tech sent four screened profiles in five days and both hires are still with us a year later.','APPROVED',true,now()),
 ('Anita Deshmukh','Plant HR Manager','Automotive Components Manufacturer',4,'Most agencies only understand IT. Amani Tech filled mechanical design and quality roles for us with candidates who actually matched the JD.','APPROVED',true,now()),
 ('Rahul Verma','SAP FICO Consultant','Placed via Amani Tech',5,'Clear communication at every step. I always knew where my application stood.','APPROVED',false,now()),
 ('Kavya Nair','Accountant','Manufacturing Group',5,'The team was patient with my questions and negotiated a fair offer on my behalf.','PENDING',false,null),
 ('Deepak Sharma','Talent Acquisition Lead','NBFC',4,'Responsive team and good quality shortlist for our FP&A roles.','PENDING',false,null);

-- ---------- Sample leads (so the admin has something to work with) ----------
insert into employer_enquiries (full_name, work_email, phone, company_name, designation, requirement_type, job_title, positions, location, work_mode, experience_required, joining_timeline, job_description, status) values
 ('Suresh Menon','suresh@saas-scaleup.example','+91 80 4000 1234','SaaS Scale-up','Head of Engineering','Contract staffing','Site Reliability Engineer',2,'Bengaluru','On-site','4–7 years','Within 30 days','Two SREs to own production reliability for a multi-tenant SaaS platform on AWS. Kubernetes, Terraform and on-call experience required.','NEW'),
 ('Anita Deshmukh','anita.d@autocomp.example','+91 44 2200 5678','Automotive Components Manufacturer','Plant HR Manager','Permanent recruitment','Quality Engineer',3,'Chennai','On-site','3–6 years','Within 60 days','Quality engineers for a two-wheeler component plant. PPAP, APQP and customer audit experience.','CONTACTED'),
 ('Neha Agarwal','neha@edtech.example','+91 20 6700 4321','EdTech Company','Sales Director','Bulk hiring','Inside Sales Executive',15,'Pune','On-site','1–3 years','Within 30 days','Fifteen inside sales executives for a new enrolment centre. Fluent English and Hindi, target-driven.','CONVERTED');

insert into vendor_enquiries (company, contact_person, email, phone, location, services, specialization, years_experience, website, status) values
 ('TalentBridge Consultants','Manish Gupta','manish@talentbridge.example','+91 98100 12121','Delhi NCR',array['Permanent recruitment','Contract staffing'],'BFSI, Fintech','5–10','talentbridge.example','PENDING'),
 ('SkillPort Campus Solutions','Lakshmi Prasad','lakshmi@skillport.example','+91 98480 34343','Hyderabad',array['Campus hiring'],'Engineering graduates','2–5','skillport.example','APPROVED');
